name: obj-det
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _tflow_select=2.3.0=mkl
  - absl-py=0.7.1=py37_0
  - astor=0.7.1=py37_0
  - blas=1.0=mkl
  - ca-certificates=2019.6.16=hecc5488_0
  - certifi=2019.6.16=py37_0
  - cycler=0.10.0=py_1
  - cython=0.29.11=py37ha925a31_0
  - freetype=2.10.0=h5db478b_0
  - gast=0.2.2=py37_0
  - grpcio=1.16.1=py37h351948d_1
  - h5py=2.9.0=py37h5e291fa_0
  - hdf5=1.10.4=h7ebc959_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.1=vc14_0
  - intel-openmp=2019.4=245
  - jpeg=9c=hfa6e2cd_1001
  - keras-applications=1.0.8=py_0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.1.0=py37he980bc4_0
  - libblas=3.8.0=8_mkl
  - libcblas=3.8.0=8_mkl
  - liblapack=3.8.0=8_mkl
  - liblapacke=3.8.0=8_mkl
  - libmklml=2019.0.3=0
  - libpng=1.6.37=h7602738_0
  - libprotobuf=3.8.0=h7bd577a_0
  - libtiff=4.0.10=h6512ee2_1003
  - libwebp=1.0.2=hfa6e2cd_2
  - lz4-c=1.8.3=he025d50_1001
  - markdown=3.1.1=py37_0
  - matplotlib=3.1.1=py37_0
  - matplotlib-base=3.1.1=py37h2852a4a_0
  - mkl=2019.4=245
  - mkl_fft=1.0.12=py37h14836fe_0
  - mkl_random=1.0.2=py37h343c172_0
  - mock=3.0.5=py37_0
  - numpy=1.16.4=py37h19fb1c0_0
  - numpy-base=1.16.4=py37hc3f5095_0
  - olefile=0.46=py_0
  - opencv=4.1.0=py37hb4945ee_5
  - openssl=1.1.1b=hfa6e2cd_2
  - pillow=6.0.0=py37h9a613e6_0
  - pip=19.1.1=py37_0
  - protobuf=3.8.0=py37h33f27b4_0
  - pyparsing=2.4.0=py_0
  - pyqt=5.9.2=py37h6538335_0
  - pyreadline=2.1=py37_1
  - python=3.7.3=h8c8aaf0_1
  - python-dateutil=2.8.0=py_0
  - qt=5.9.7=hc6833c9_1
  - scipy=1.2.1=py37h29ff71c_0
  - setuptools=41.0.1=py37_0
  - sip=4.19.8=py37h6538335_1000
  - six=1.12.0=py37_0
  - sqlite=3.28.0=he774522_0
  - tensorboard=1.13.1=py37h33f27b4_0
  - tensorflow=1.13.1=mkl_py37h9463c59_0
  - tensorflow-base=1.13.1=mkl_py37hcaf7020_0
  - tensorflow-estimator=1.13.0=py_0
  - termcolor=1.1.0=py37_1
  - tk=8.6.9=hfa6e2cd_1002
  - vc=14.1=h21ff451_3
  - vs2015_runtime=15.5.2=3
  - werkzeug=0.15.4=py_0
  - wheel=0.33.4=py37_0
  - wincertstore=0.2=py37_0
  - xz=5.2.4=h2fa13f4_1001
  - zlib=1.2.11=h62dcd97_3
  - zstd=1.4.0=hd8a0e53_0
  - pip:
    - altair==3.2.0
    - argh==0.26.2
    - attrs==19.2.0
    - base58==1.0.3
    - blinker==1.4
    - boto3==1.9.243
    - botocore==1.12.243
    - chardet==3.0.4
    - click==7.0
    - decorator==4.4.0
    - docutils==0.15.2
    - entrypoints==0.3
    - enum-compat==0.0.2
    - future==0.17.1
    - idna==2.8
    - jinja2==2.10.3
    - jmespath==0.9.4
    - jsonschema==3.0.2
    - markupsafe==1.1.1
    - pandas==0.25.1
    - pathtools==0.1.2
    - pyrsistent==0.15.4
    - pytz==2019.3
    - pyyaml==5.1.2
    - requests==2.22.0
    - s3transfer==0.2.1
    - streamlit==0.47.4
    - toml==0.10.0
    - toolz==0.10.0
    - tornado==5.1.1
    - tzlocal==2.0.0
    - urllib3==1.25.6
    - validators==0.14.0
    - watchdog==0.9.0
prefix: C:\Users\festevem\AppData\Local\Continuum\anaconda3\envs\obj-det

